add error checking logic to catch unmountable mount point.
Signed-off-by: Wolf Noble <wnoble@datapipe.com>

diff --git a/templates/usr/local/scripts/meta-backup.sh.erb b/templates/usr/local/scripts/meta-backup.sh.erb
--- a/templates/usr/local/scripts/meta-backup.sh.erb
+++ b/templates/usr/local/scripts/meta-backup.sh.erb
@@ -7,21 +7,31 @@ send        = scope.lookupvar('xenserver::backup::enable_email')
 -%>
 #!/bin/bash
 #This script managed by puppet. Manual changes will be reverted
-
-rm -f <%=mountpoint-%>/<%=cluster-%>-metadata.bak
+#
+#mount the filesystem
+mount <%=mountpoint%>
+if [ $? -eq 0 ]; then
+  rm -f <%=mountpoint-%>/<%=cluster-%>-metadata.bak
 <% hypervisors.flatten.each do |host| -%>
-rm -f <%=mountpoint-%>/<%=host-%>-host-backup.bak
+  rm -f <%=mountpoint-%>/<%=host-%>-host-backup.bak
 <%end-%>
-
-/opt/xensource/bin/xe pool-dump-database file-name=<%=mountpoint-%>/<%=cluster-%>-metadata.bak
+  /opt/xensource/bin/xe pool-dump-database file-name=<%=mountpoint-%>/<%=cluster-%>-metadata.bak
 <% hypervisors.flatten.each do |host| -%>
-/opt/xensource/bin/xe host-backup file-name=<%=mountpoint-%>/<%=host-%>-host-backup.bak host=<%=host%>
+  /opt/xensource/bin/xe host-backup file-name=<%=mountpoint-%>/<%=host-%>-host-backup.bak host=<%=host%>
 <%end-%>
-rm -f /tmp/metadatamessage.tmp
+  rm -f /tmp/metadatamessage.tmp
 <% if send -%>
-/bin/cat /usr/local/etc/mailheader.txt > /tmp/metadatamessage.tmp
-/bin/echo "Subject: Metadata backed up for <%=cluster%>" >> /tmp/metadatamessage.tmp
-/bin/echo "Here is the cleanuplog from the Xen Cluster" >> /tmp/metadatamessage.tmp
-/bin/ls  <%=mountpoint-%>/*.bak >> /tmp/metadatamessage.tmp
-/usr/sbin/ssmtp  <%=address-%> < /tmp/metadatamessage.tmp&& rm /tmp/metadatamessage.tmp
+  /bin/cat /usr/local/etc/mailheader.txt > /tmp/metadatamessage.tmp
+  /bin/echo "Subject: Metadata backed up for <%=cluster%>" >> /tmp/metadatamessage.tmp
+  /bin/echo "Here is the metadata backup log from the Xen Cluster" >> /tmp/metadatamessage.tmp
+  /bin/ls  <%=mountpoint-%>/*.bak >> /tmp/metadatamessage.tmp
+  /usr/sbin/ssmtp  <%=address-%> < /tmp/metadatamessage.tmp&& rm /tmp/metadatamessage.tmp
 <%end -%>
+else
+  rm -f /tmp/metadatamessage.tmp
+<% if send -%>
+  /bin/cat /usr/local/etc/mailheader.txt > /tmp/metadatamessage.tmp
+  /bin/echo "Subject: <%=cluster-%> Could not mount backup" >> /tmp/metadatamessage.tmp
+  /bin/echo "something's broke!" >> /tmp/metadatamessage.tmp
+  /usr/sbin/ssmtp  <%=address-%> < /tmp/metadatamessage.tmp&& rm /tmp/metadatamessage.tmp
+fi
